### ISSUE TITLE
There's a big difference between my results and yours

### ISSUE THREAD

**Issue by zhangrunjiang** [clovaai/rainbow-memory#11]
hi，I  ran "cifar10", but the results were significantly different from yours .  Can you help me see what I did wrong？
I set the parameters according to the file “experiment.sh”:
--mode
"rm"
--mem_manage
"default"
--exp_name
"blurry10"
--dataset
"cifar10"
--stream_env
"online"
"--init_opt"
--topk
1
--n_tasks
5
--n_cls_a_task
2
--n_init_cls
10
--rnd_seed
1
--model_name
resnet18
--opt_name
"sgd"
--sched_name
"cos"
--lr
0.05
--batchsize
256
--n_worker
0
--n_epoch
16
--memory_size
500
--transform
"cutmix autoaug"
--uncert_metric
"vr_randaug"
--feature_size
2048
"--distilling"
--joint_acc
0.0
And I recorded the output of the whole experiment :
[result.txt](https://github.com/clovaai/rainbow-memory/files/8194152/result.txt)

**Comment by hwany-j** [comment]
Hello! First, thank you for interesting my research rainbow memory. I carefully look into `result.txt`, and I found that it doesn't reflect `AutoAugment` in train_transform. In my experimental environment, the code can reflect `transform` argument well . Hence, I recommend you to make environment without error.
