### ISSUE TITLE
One quesion about accuracy in table 3：why online is better than offline?

### ISSUE THREAD

**Issue by zhl98** [clovaai/rainbow-memory#12]
Hi! I am very interested in your work. But I have a question. Rainbow Memory get 66.25 in Blurry0(disjoint) online model  in table3, bet get 61.91 in offline model . Generally, the online effect is worse than the offline effect, because the data of the current task can only be used once, and the data can only be reused in memory. However, there are not so many restrictions under the offline setting. Can you tell me why online is better than offline?

**Comment by hwany-j** [comment]
Hello! Thank you for being interesting in our paper! 
As you know, each task does not share the classes in the disjoint setup, so the dataset of the task has a class imbalance problem. In offline setup, we can observe the data of the task infinitely unlike in online setup, so it is needed to handle the class imbalance problem to get a better result. However, Rainbow Memory only focuses on sampling diversified examples and diversifying features by augmentation, so it has worse performance in an offline set-up of the class imbalance problem than in an online set-up.

**Comment by zhl98** [comment]
OK, thank you very much for your answer.
