### ISSUE TITLE
Different results from yours

### ISSUE THREAD

**Issue by Taylorfire** [clovaai/rainbow-memory#14]
Hi! I ran experiment.sh by only changing the method name from "rm" to "icarl". I suppose the results should be the online results of icarl on cifar10 with buffer_size=500. However, I got different results from yours, and the average accuracy is 57.71% (in paper it is reported as 45.98±3.04%) 
Here is the log file I got, could you please tell me that if there is anything wrong?
[icarl_default_online_msz500_rnd1_cutmix_autoaug.txt](https://github.com/clovaai/rainbow-memory/files/10957954/icarl_default_online_msz500_rnd1_cutmix_autoaug.txt)

**Comment by hwany-j** [comment]
Hello! In Table.2 in our paper, the baselines are not used in DA, which is a combination of CutMix and AutoAug. Hence, you should turn off the augmentation technique if you want to get the result that the paper is reported.

**Comment by Taylorfire** [comment]
> Hello! In Table.2 in our paper, the baselines are not used in DA, which is a combination of CutMix and AutoAug. Hence, you should turn off the augmentation technique if you want to get the result that the paper is reported.

Oh, I see. Thanks for your soon reply! I will correct this error and try again on these baseline methods. 
Would you mind me keeping this issue open for a few days in case I have other problems reproducing the results of experiments?
