### ISSUE TITLE
Why considering blurry setting is better than the disjoint setting?

### ISSUE THREAD

**Issue by b224618** [clovaai/rainbow-memory#2]
Hi, the proposed rainbow-memory is impressive and inspiring. And I'm pretty curious about the setting. If a model is trained on disjoint setting, won't the blurry setting be eaiser for the model? In my understanding, in the disjoint setting, the distributions of different tasks are more different, causing more severe catastrophic forgetting and seemingly more difficult than the blurry setting in which the tasks share classes.
I'd really appreciate it if I can get any response on this to help me better understand this problem!

**Comment by jchoivision** [comment]
Hi! Thank you for the great question!
I would say that the disjoint setting and the blurry setting are rather different than more or less challenging. The disjoint setting is less realistic as we and GDumb paper claimed. I also think that the disjoint setting may exacerbate the forgetting but this setting may not happen in the real deployment situation. Note that we believe the blurry setting makes the intransigence worse as the number of sample would be smaller than that in disjoint setting.
