### ISSUE TITLE
repeat experiment on online disjoint-CIL setup

### ISSUE THREAD

**Issue by ray0nv3rt** [clovaai/rainbow-memory#6]
Hi, I have been trying to repeat the experiment on online disjoint-CIL setup (table 3 in the article). But even with data augmentation, the last accuracy I get using all the three seeds are around 40%.  The change that I did to the experiment.sh is changing the EXP from blurry10 to disjoint. Am I miss some setting that cause this?

**Comment by hwany-j** [comment]
Hi. First of all, thank you for your interest in our paper. I double-checked our method on online disjoint-CIL setup (table3 in the article) after you posted the issue, but the result is as same as table 3. I also changed the EXP from blurry10 to disjoint in `experiment.sh`. Hence, to avoid something different from our repo, I recommend you that you re-clone our repository and change only `EXP = disjoint` in `experiment.sh`.  Thank you for your interest and I wish our repo will help your research 🙏
