### ISSUE TITLE
How to make blurry-M datasets?

### ISSUE THREAD

**Issue by GG-Bond-007** [clovaai/rainbow-memory#8]
Hi! I am so interested in your work. And I want to do some research on other datasets with blurry setup. So I would like to ask you for help if you can share the code for making the burry dataset. I will appreciate it! Thank you!

**Comment by hwany-j** [comment]
Hello! Sorry for the late reply. Unfortunately, the code for making the blurry dataset is only focused on the public dataset, such as CIFARs, ImageNet, etc, so I need to clean up the code. Would you wait for a while for cleaning up the code?

**Comment by GG-Bond-007** [comment]
ok

**Comment by zackschen** [comment]
Hi! I am so interested in your work, too. Do you clean up the code completely? Thank you for your work!

**Comment by hwany-j** [comment]
Hello! Sorry for the late update in terms of this issue. I updated the notebook file that makes the disjoint/blurry dataset of each task. Thanks for your interest in my research :)
