### ISSUE TITLE
One question about blurry setup

### ISSUE THREAD

**Issue by GG-Bond-007** [clovaai/rainbow-memory#9]
Hi! I am very interested in your work. But I have a question. At the top of Figure 1 in the paper, category 3 does not appear in the previous task, but only appears in the current task. But in your experiment, the sample category of each task includes the category of the entire data set. I think this is a contradiction. So I want to ask in the blurry settings, does the previous task include the categories that are major categories of the following tasks? In your code, they are included, but Figure 1 does not seem to mean this. Is the picture wrong?

**Comment by hwany-j** [comment]
Hello! Thank you for your interest in my research. In figure 1, we just want to show you for blurry setup in general, and `blurry setup` in the experiment we've conducted is one of the blurry types. Although the blurry setup in figure 1 is not exactly suitable for our experiment setup as you mentioned, we want to share that continual learning can have a more practical setup than `disjoint`, and there can be other setups that are more practical than our `blurry` setup which is used in experiment section.

**Comment by GG-Bond-007** [comment]
Thank you for your reply, I understand.
